import React from 'react';
import { formatNaira } from '../utils/formatters';
import { formatReconciliationDate, VAT_RATE } from '../data/salesReportsData';

/**
 * Printable daily reconciliation sheet (Z-report / end-of-day cash sheet).
 * Rendered off-screen and revealed only by the `@media print` rule in index.css,
 * matching the 80mm thermal receipt print strategy.
 */
export default function ReconciliationSheet({
  store,
  storeSettings,
  rangeLabel,
  window,
  summary,
  trendRows,
}) {
  const rows = trendRows;

  return (
    <div
      id="printable-reconciliation"
      className="fixed -left-[10000px] top-0 w-[820px] bg-white p-8 text-slate-900 font-sans"
    >
      {/* Sheet header */}
      <div className="flex items-start justify-between border-b-2 border-slate-900 pb-4">
        <div>
          <h1 className="text-lg font-bold">{storeSettings?.profile?.storeName || 'Okonkwo & Sons Ltd'}</h1>
          <p className="text-xs">{store?.name} &middot; {store?.address}</p>
          <p className="text-xs">
            TIN: {storeSettings?.profile?.tinNumber || '23849102-0001'} &middot; CAC:{' '}
            {storeSettings?.profile?.cacNumber || 'RC-1849204'}
          </p>
        </div>
        <div className="text-right">
          <h2 className="text-sm font-bold uppercase tracking-wide">Daily Reconciliation Sheet</h2>
          <p className="text-xs">Period: {rangeLabel}</p>
          <p className="text-xs font-mono">
            {formatReconciliationDate(window.start)} &rarr; {formatReconciliationDate(window.end)}
          </p>
          <p className="text-[10px] mt-1">
            Printed {new Date().toLocaleString('en-GB')} &middot; Generated by StockNaira
          </p>
        </div>
      </div>

      {/* Channel block totals */}
      <table className="w-full mt-5 text-xs border-collapse">
        <thead>
          <tr className="border-b border-slate-300">
            <th className="text-left py-2">Payment Channel</th>
            <th className="text-right py-2">Volume (&#8358;)</th>
            <th className="text-right py-2">Share</th>
            <th className="text-left py-2 pl-6">Settlement / Audit Note</th>
          </tr>
        </thead>
        <tbody className="align-top">
          <tr className="border-b border-slate-200">
            <td className="py-2 font-semibold">Cash Sales (Counter Drawer)</td>
            <td className="py-2 text-right font-mono">{formatNaira(summary.cashSales)}</td>
            <td className="py-2 text-right font-mono">{summary.cashShare.toFixed(1)}%</td>
            <td className="py-2 pl-6 text-[11px] text-slate-600">
              Counted against opening float. Variance to be signed below.
            </td>
          </tr>
          <tr className="border-b border-slate-200">
            <td className="py-2 font-semibold">POS Terminal (Moniepoint)</td>
            <td className="py-2 text-right font-mono">{formatNaira(summary.posSales)}</td>
            <td className="py-2 text-right font-mono">
              {summary.digitalSales > 0
                ? ((summary.posSales / summary.digitalSales) * 100).toFixed(1)
                : '0.0'}
              %
            </td>
            <td className="py-2 pl-6 text-[11px] text-slate-600">
              Card settlements batched for next-day remittance.
            </td>
          </tr>
          <tr className="border-b border-slate-200">
            <td className="py-2 font-semibold">NIP Bank Transfer (Webhook Verified)</td>
            <td className="py-2 text-right font-mono">{formatNaira(summary.transferSales)}</td>
            <td className="py-2 text-right font-mono">
              {summary.digitalSales > 0
                ? ((summary.transferSales / summary.digitalSales) * 100).toFixed(1)
                : '0.0'}
              %
            </td>
            <td className="py-2 pl-6 text-[11px] text-slate-600">
              Matched against NIP session references before goods release.
            </td>
          </tr>
          <tr className="border-b-2 border-slate-900">
            <td className="py-2 font-bold">Total Gross Sales</td>
            <td className="py-2 text-right font-mono font-bold">{formatNaira(summary.grossSales)}</td>
            <td className="py-2 text-right font-mono">100%</td>
            <td className="py-2 pl-6 text-[11px]">{summary.transactions} transactions issued</td>
          </tr>
          <tr className="border-b border-slate-200">
            <td className="py-2">Less: VAT Collected ({VAT_RATE * 100}%)</td>
            <td className="py-2 text-right font-mono">-{formatNaira(summary.vat)}</td>
            <td className="py-2 text-right font-mono text-[11px]">FRS/LIRS remittance</td>
            <td className="py-2 pl-6 text-[11px] text-slate-600">
              VAT output to be remitted via FIRS filing portal.
            </td>
          </tr>
          <tr>
            <td className="py-2 font-bold">Net Sales Payable to Merchant</td>
            <td className="py-2 text-right font-mono font-bold">{formatNaira(summary.netSales)}</td>
            <td className="py-2 text-right font-mono text-[11px]">-</td>
            <td className="py-2 pl-6 text-[11px] text-slate-600">
              Average basket {formatNaira(summary.avgBasket)}
            </td>
          </tr>
        </tbody>
      </table>

      {/* Day-by-day ledger */}
      <h3 className="text-xs font-bold uppercase tracking-wide mt-6 mb-2">
        Day-by-Day Revenue Ledger
      </h3>
      <table className="w-full text-[11px] border-collapse">
        <thead>
          <tr className="border-b border-slate-300 text-left">
            <th className="py-1.5">Date</th>
            <th className="py-1.5 text-right">Cash (&#8358;)</th>
            <th className="py-1.5 text-right">POS (&#8358;)</th>
            <th className="py-1.5 text-right">Transfer (&#8358;)</th>
            <th className="py-1.5 text-right">Gross (&#8358;)</th>
            <th className="py-1.5 text-right">VAT (&#8358;)</th>
            <th className="py-1.5 text-right">Txns</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={row.date} className="border-b border-slate-100">
              <td className="py-1.5 font-mono">
                {row.label} ({row.weekday})
              </td>
              <td className="py-1.5 text-right font-mono">{formatNaira(row.cash)}</td>
              <td className="py-1.5 text-right font-mono">{formatNaira(row.pos)}</td>
              <td className="py-1.5 text-right font-mono">{formatNaira(row.transfer)}</td>
              <td className="py-1.5 text-right font-mono font-semibold">
                {formatNaira(row.total)}
              </td>
              <td className="py-1.5 text-right font-mono">{formatNaira(row.vat)}</td>
              <td className="py-1.5 text-right font-mono">{row.transactions}</td>
            </tr>
          ))}
          <tr className="border-t-2 border-slate-900">
            <td className="py-1.5 font-bold">TOTALS</td>
            <td className="py-1.5 text-right font-mono font-bold">{formatNaira(summary.cashSales)}</td>
            <td className="py-1.5 text-right font-mono font-bold">{formatNaira(summary.posSales)}</td>
            <td className="py-1.5 text-right font-mono font-bold">
              {formatNaira(summary.transferSales)}
            </td>
            <td className="py-1.5 text-right font-mono font-bold">
              {formatNaira(summary.grossSales)}
            </td>
            <td className="py-1.5 text-right font-mono font-bold">{formatNaira(summary.vat)}</td>
            <td className="py-1.5 text-right font-mono font-bold">{summary.transactions}</td>
          </tr>
        </tbody>
      </table>

      {/* Signature block */}
      <div className="grid grid-cols-3 gap-6 mt-8 text-[11px]">
        <div>
          <p className="border-b border-slate-400 pb-6" />
          <p className="pt-1 font-semibold">Cashier / Shift Officer</p>
        </div>
        <div>
          <p className="border-b border-slate-400 pb-6" />
          <p className="pt-1 font-semibold">Branch Manager</p>
        </div>
        <div>
          <p className="border-b border-slate-400 pb-6" />
          <p className="pt-1 font-semibold">Auditor / Accountant</p>
        </div>
      </div>
      <p className="text-[10px] text-slate-500 mt-4">
        All bank transfer lines above were matched against live NIP webhook sessions. Any variance
        must be documented before the drawer is closed for the day.
      </p>
    </div>
  );
}
